format=R36OS_NATIVE_C02_BUILD_V1
suite=trixie
architecture=arm64
snapshot=20261001T082322Z
snapshot_url=https://snapshot.debian.org/archive/debian/20261001T082322Z/
components=main
variant=minbase
install_recommends=no
prototype_root=/r36state/r36os-next/rootfs
kernel_release=6.12.94-r36os-k1
kernel_owned_by=r36os
userspace_base=Debian_13_trixie_arm64
