format=R36OS_REMOTE_UPDATE_V1
repo=Hewitt554/R36OS-K1-Build
available=yes
channel=alpha
version=0.5.50.0
base_version=0.5.49.0
filename=00-R36OS-Alpha5R50-RootConsumedKernelStatus-FromR49.r36upd
size_bytes=22183
sha256=5a41efe1b5019bfb2c8b9166bffd48c663997121e90a8a58f59b1e901f7072f0
url=https://github.com/Hewitt554/R36OS-K1-Build/releases/download/alpha5r48/00-R36OS-Alpha5R50-RootConsumedKernelStatus-FromR49.r36upd
candidate_id=e551eb6598d6da7a8e8320e9
kernel_release=6.12.94-r36os-k1
